# Site Settings
title: Alan Crawford
email: a.crawford.11@ucl.ac.uk
description: >
  Welcome to my homepage
baseurl: ""
url: "https://alancrawford.github.io"
github_username:  alancrawford
port: 8080
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
